---
name: Build and Deploy React App to S3 Bucket
on: #Qual ação irá fazer o workflow funcionar, no caso, um push na branch main.
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      DIST: dist #Qual pasta você irá enviar pra AWS

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Static Website
        run: npm run build
        env:
          VITE_API_URL: ${{ vars.API_URL }}

      - name: Copy files to the production website with AWS CLI
        run: |
          aws s3 sync --delete ${{ env.DIST }}/assets s3://${{ vars.S3_BUCKET_NAME }}/assets --cache-control "max-age=31536000"
          aws s3 sync ${{ env.DIST }} s3://${{ vars.S3_BUCKET_NAME }} --exclude "assets/*"

      - name: Create an Invalidation on Cloudfront with AWS CLI
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.CLOUDFRONT_DIST_ID }} \
          --paths "/*"
